# Generated by Django 2.2 on 2022-01-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20211228_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expiry',
        ),
    ]
