# Generated by Django 2.2 on 2022-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_remove_emailverification_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
