# Generated by Django 2.2 on 2022-01-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_emailverification_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='deleted',
        ),
    ]
