# Generated by Django 2.2 on 2022-01-05 07:51

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerboard',
            name='temp_deck',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=17, validators=[django.core.validators.MaxValueValidator(100000000000000.0), django.core.validators.MinValueValidator(0.001)]), default=[], size=100),
            preserve_default=False,
        ),
    ]
