# Generated by Django 2.2 on 2022-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0002_pokerboard_temp_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokerboard',
            name='deck',
        ),
    ]
