# Generated by Django 2.2 on 2022-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0003_remove_pokerboard_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokerboard',
            old_name='temp_deck',
            new_name='deck',
        ),
    ]
