# Generated by Django 2.2 on 2022-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0005_auto_20220111_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerticket',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pokerboardinvitation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userpokerboard',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
