# Generated by Django 2.2 on 2022-01-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0006_auto_20220113_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerticket',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='pokerboard',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='pokerboardinvitation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userpokerboard',
            name='deleted',
        ),
    ]
