# Generated by Django 2.2 on 2022-01-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0007_auto_20220113_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerboard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
