# Generated by Django 2.2 on 2022-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0008_pokerboard_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpokerboard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
