# Generated by Django 2.2 on 2022-01-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboards', '0009_userpokerboard_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
