# Generated by Django 2.2 on 2022-01-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220113_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userjiratoken',
            name='deleted',
        ),
    ]
